[Web] Bump web-tokenizer to 0.1.6 (#67)
This PR bumps web-tokenizer to 0.1.6 to reflect the latest HEAD changes.

Without bumping this, WebLLM would run into RUST-related error (thread '<unnamed>' panicked at src/lib.rs:26:50:), likely due to the newly compiled weights and tokenizer files in mlc-ai's HF repo are not matching with the web-tokenizer package.

Unrelatedly, we also upstream package-lock.json